name: wandering_compass_client
description: a portable compass for wanderers; a primitive calendar for aliens
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.38.0

resolution: workspace

dependencies:
  bloc: ^9.0.1
  build_runner: ^2.10.2
  clock: ^1.1.2
  dart_mappable: ^4.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  intl: ^0.20.2
  schedule_repository:
    path: 'packages/schedule_repository'
  shared: 0.0.1

dev_dependencies:
  bloc_test: ^10.0.0
  dart_mappable_builder: ^4.6.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
